"""
Integration tests for 256-bit encryption compatibility.

These tests verify that the Python SDK's 256-bit implementation is compatible
with the TypeScript SDK by using known test vectors and edge cases.
"""

import pytest
from coti.crypto_utils import prepare_it_256, decrypt_uint256, generate_aes_key, create_ciphertext_256
import os


# Test vectors for cross-SDK compatibility
# These should match the TypeScript SDK's expected behavior
class TestCrossSdkCompatibility:
    """Tests to ensure compatibility with TypeScript SDK"""
    
    def test_ciphertext_structure(self):
        """Verify ciphertext structure matches TypeScript SDK format"""
        plaintext = 123456789012345678901234567890
        aes_key = generate_aes_key().hex()
        sender = "0x" + "1" * 40
        contract = "0x" + "2" * 40
        selector = "0x12345678"
        signing_key = os.urandom(32)
        
        it = prepare_it_256(plaintext, aes_key, sender, contract, selector, signing_key)
        
        # Verify structure matches expected TypeScript format
        assert 'ciphertext' in it
        assert 'signature' in it
        assert 'ciphertextHigh' in it['ciphertext']
        assert 'ciphertextLow' in it['ciphertext']
        
        # Verify both parts are integers
        assert isinstance(it['ciphertext']['ciphertextHigh'], int)
        assert isinstance(it['ciphertext']['ciphertextLow'], int)
        assert isinstance(it['signature'], bytes)
    
    def test_ciphertext_blob_size(self):
        """Verify the internal ciphertext blob is 64 bytes as expected"""
        plaintext = (1 << 200) + 42
        aes_key_bytes = generate_aes_key()
        
        ct_blob = create_ciphertext_256(plaintext, aes_key_bytes)
        
        # Should be 64 bytes: high_ct(16) + high_r(16) + low_ct(16) + low_r(16)
        assert len(ct_blob) == 64
        
        # Verify it can be split into 4 equal parts
        assert len(ct_blob[:16]) == 16  # high_ct
        assert len(ct_blob[16:32]) == 16  # high_r
        assert len(ct_blob[32:48]) == 16  # low_ct
        assert len(ct_blob[48:64]) == 16  # low_r
    
    def test_deterministic_encryption_with_same_plaintext(self):
        """Verify that encrypting the same plaintext produces different ciphertexts (due to random 'r')"""
        plaintext = 987654321
        aes_key = generate_aes_key().hex()
        sender = "0x" + "a" * 40
        contract = "0x" + "b" * 40
        selector = "0x11223344"
        signing_key = os.urandom(32)
        
        it1 = prepare_it_256(plaintext, aes_key, sender, contract, selector, signing_key)
        it2 = prepare_it_256(plaintext, aes_key, sender, contract, selector, signing_key)
        
        # Ciphertexts should be different due to random 'r'
        assert (it1['ciphertext']['ciphertextHigh'] != it2['ciphertext']['ciphertextHigh'] or 
                it1['ciphertext']['ciphertextLow'] != it2['ciphertext']['ciphertextLow'])
        
        # But both should decrypt to the same plaintext
        decrypted1 = decrypt_uint256(it1['ciphertext'], aes_key)
        decrypted2 = decrypt_uint256(it2['ciphertext'], aes_key)
        
        assert decrypted1 == plaintext
        assert decrypted2 == plaintext
    
    def test_known_test_vectors(self):
        """
        Test with known values that could be shared between SDKs.
        
        Note: In a real integration test, these would be test vectors
        generated by the TypeScript SDK and verified here.
        """
        test_cases = [
            0,
            1,
            255,
            256,
            65535,
            65536,
            (1 << 128) - 1,  # Max 128-bit
            1 << 128,        # Min 129-bit
            (1 << 256) - 1,  # Max 256-bit
        ]
        
        aes_key = generate_aes_key().hex()
        
        for plaintext in test_cases:
            sender = "0x" + "1" * 40
            contract = "0x" + "2" * 40
            selector = "0x12345678"
            signing_key = os.urandom(32)
            
            it = prepare_it_256(plaintext, aes_key, sender, contract, selector, signing_key)
            decrypted = decrypt_uint256(it['ciphertext'], aes_key)
            
            assert decrypted == plaintext, f"Failed for test case: {plaintext}"
    
    def test_high_part_only_nonzero(self):
        """Test value where only high 128 bits are non-zero"""
        # Value = 0xFF...FF << 128 (high part all ones, low part all zeros)
        plaintext = ((1 << 128) - 1) << 128
        
        aes_key = generate_aes_key().hex()
        sender = "0x" + "1" * 40
        contract = "0x" + "2" * 40
        selector = "0x12345678"
        signing_key = os.urandom(32)
        
        it = prepare_it_256(plaintext, aes_key, sender, contract, selector, signing_key)
        decrypted = decrypt_uint256(it['ciphertext'], aes_key)
        
        assert decrypted == plaintext
    
    def test_low_part_only_nonzero(self):
        """Test value where only low 128 bits are non-zero"""
        # Value = 0xFF...FF (low part all ones, high part all zeros)
        plaintext = (1 << 128) - 1
        
        aes_key = generate_aes_key().hex()
        sender = "0x" + "1" * 40
        contract = "0x" + "2" * 40
        selector = "0x12345678"
        signing_key = os.urandom(32)
        
        it = prepare_it_256(plaintext, aes_key, sender, contract, selector, signing_key)
        decrypted = decrypt_uint256(it['ciphertext'], aes_key)
        
        assert decrypted == plaintext
    
    def test_alternating_bit_pattern(self):
        """Test with alternating bit patterns"""

        high = 0xAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        low = 0x55555555555555555555555555555555
        plaintext = (high << 128) | low
        
        aes_key = generate_aes_key().hex()
        sender = "0x" + "1" * 40
        contract = "0x" + "2" * 40
        selector = "0x12345678"
        signing_key = os.urandom(32)
        
        it = prepare_it_256(plaintext, aes_key, sender, contract, selector, signing_key)
        decrypted = decrypt_uint256(it['ciphertext'], aes_key)
        
        assert decrypted == plaintext


class TestMultipleKeyScenarios:
    """Test encryption/decryption with different AES keys"""
    
    def test_different_keys_produce_different_results(self):
        """Verify that different AES keys produce different ciphertexts"""
        plaintext = 123456789
        key1 = generate_aes_key().hex()
        key2 = generate_aes_key().hex()
        
        sender = "0x" + "1" * 40
        contract = "0x" + "2" * 40
        selector = "0x12345678"
        signing_key = os.urandom(32)
        
        it1 = prepare_it_256(plaintext, key1, sender, contract, selector, signing_key)
        it2 = prepare_it_256(plaintext, key2, sender, contract, selector, signing_key)
        
        # Different keys should produce different ciphertexts
        assert (it1['ciphertext']['ciphertextHigh'] != it2['ciphertext']['ciphertextHigh'] or
                it1['ciphertext']['ciphertextLow'] != it2['ciphertext']['ciphertextLow'])
    
    def test_wrong_key_produces_wrong_plaintext(self):
        """Verify that decrypting with wrong key doesn't recover original plaintext"""
        plaintext = 987654321
        correct_key = generate_aes_key().hex()
        wrong_key = generate_aes_key().hex()
        
        sender = "0x" + "1" * 40
        contract = "0x" + "2" * 40
        selector = "0x12345678"
        signing_key = os.urandom(32)
        
        it = prepare_it_256(plaintext, correct_key, sender, contract, selector, signing_key)
        
        # Decrypt with correct key
        decrypted_correct = decrypt_uint256(it['ciphertext'], correct_key)
        assert decrypted_correct == plaintext
        
        # Decrypt with wrong key
        decrypted_wrong = decrypt_uint256(it['ciphertext'], wrong_key)
        assert decrypted_wrong != plaintext
